version: '3.6'

# volumes:
#   db:
#   app:

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ${PWD}/data/db:/var/lib/postgresql/data/:rw
    env_file:
      - db.env

  app:
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - ${PWD}/data/app:/var/www/html:rw
      - ${PWD}/data/extra:/mnt/custom_volume:rw
    restart: always
    env_file:
      - db.env
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - POSTGRES_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.0.107:8080
    depends_on:
      - db